export enum Permission {
  AdminAccess = 'admin.access',
  UsersManage = 'users.manage',
  PermissionsManage = 'permissions.manage',
  LeadsManage = 'leads.manage',
  BookingsManage = 'bookings.manage',
  BookingsReview = 'bookings.review',
  CoursesManage = 'courses.manage',
  AttendanceManage = 'attendance.manage',
  MaterialsManage = 'materials.manage',
  UnitsManage = 'units.manage',
  EquipmentsManage = 'equipments.manage',
  EventsManage = 'events.manage',
  NotificationsManage = 'notifications.manage',
  PortalEdit = 'portal.edit',
  SiteEdit = 'site.edit',
}
